### ISSUE TITLE
No parse_magnet_uri() function to parses out information from the magnet link

### ISSUE THREAD

**Issue by wiktordev** [lyssdod/node-libtorrent#2]
Hello, 

To add the magnet link, it need to parse the trackers and DHT routers from magnet link.
There is parse_magnet_uri() function to do it in libtorrent API. But no function to respond to it in this package.
Hope that function will be implemented soon.

Thanks,
Wiktor.

**Comment by lyssdod** [comment]
Hello,

You can use for example this package: https://www.npmjs.com/package/parse-torrent or use regular expression to extract trackers from the link.

**Comment by lyssdod** [comment]
Origin code uses regular expression as well, so there's absolutely no magic about that.

That's how dht routers are added: https://github.com/arvidn/libtorrent/blob/9e1305ed7550d23dacf291744542d9fbb9896635/src/magnet_uri.cpp#L256

And that's how are trackers: https://github.com/arvidn/libtorrent/blob/9e1305ed7550d23dacf291744542d9fbb9896635/src/magnet_uri.cpp#L195

**Comment by wiktordev** [comment]
Thanks for your comment.
