### ISSUE TITLE
Need to add alert types for torrent pause/resume

### ISSUE THREAD

**Issue by wiktordev** [lyssdod/node-libtorrent#3]
Hello.

I need to change the state of local torrent handle when user pause/resume the torrent.
I think it need to catch the events of 'torrent_paused_alert' and 'torrent_resumed_alert' when the pause/resume action is done.

Thanks,
Wiktor.

**Comment by lyssdod** [comment]
You can just use `pause` and `resume` methods for it, there's no need to catch the alert when you have the control of handle
